[package]
name = "snarkos-storage"
version = "1.3.9"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Storage for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[features]
default = [ "rocksdb_storage" ]
rocksdb_storage = [ "rocksdb" ]
mem_storage = [ ]
test = [ ]

[dependencies.snarkvm-algorithms]
version = "0.5.4"

[dependencies.snarkvm-dpc]
version = "0.5.4"

[dependencies.parking_lot]
version = "0.11"

[dependencies.snarkvm-parameters]
version = "0.5.4"

[dependencies.snarkvm-utilities]
version = "0.5.4"

[dependencies.snarkos-parameters]
path = "../parameters"
version = "1.3.9"

[dependencies.anyhow]
version = "1.0.40"

[dependencies.bincode]
version = "1.3.1"

[dependencies.hex]
version = "0.4.2"

[dependencies.rand]
version = "0.8"

[dependencies.arc-swap]
version = "1.2"

[dependencies.rocksdb]
version = "0.16.0"
optional = true

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.thiserror]
version = "1.0"

[dependencies.async-trait]
version = "0.1"

[dependencies.tracing]
default-features = false
features = [ "log" ]
version = "0.1"

[dev-dependencies.snarkos-consensus]
path = "../consensus"

[dev-dependencies.snarkvm-curves]
version = "0.5.4"

[dev-dependencies.snarkos-testing]
path = "../testing"

[dev-dependencies.tokio]
version = "1"

[dev-dependencies.tracing-subscriber]
version = "0.2"
